### ISSUE TITLE
Support JavaScript IR Compiler

### ISSUE THREAD

**Issue by davidtaylor-juul** [JuulLabs/kable#106]
To fully support Kotlin MPP there is a need to upgrade to Kotlin 1.5.x and enable compilation for both LEGACY and IR artifacts for the JavaScript target.

This may also require/allow changing from `binaries.executable()` to `binaries.library()` packaging in the `js() { }` Gradle block.

**Comment by twyatt** [comment]
After I've tested #100 a bit more and merge it, then I'll give enabling IR a try. 👍

**Comment by SebastianAigner** [comment]
Hi folks, Sebastian here, Kotlin/JS dev advocate at JetBrains! Awesome to see you're working on supporting the IR compiler. Please don't hesitate to reach out if you run into any trouble – we want to make the transition to the new compiler backend as smooth as possible :)

Feel free to reach out in the Kotlinlang Slack, for example, or via my other channels: https://kotlinlang.slack.com/team/UJ3MHFMQD
