### ISSUE TITLE
`connect` should not attempt to connect if BLE is off

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/kable#136]
#133 added support for explicitly closing BLE connections when BLE is turned off on the phone, but testing (with a Pixel 3a running Android 11) the functionality on the [SensorTag sample](https://github.com/JuulLabs/sensortag) resulted in the auto-reconnect reconnecting upon BLE being turned off.

Admittedly, it is super strange that Android allows a connection to be re-established while BLE is off, but Kable should probably handle this and prevent `connect` from reconnecting while BLE is off.

**Comment by cedrickcooke** [comment]
The weirdness here is psuedo-documented once you dive into the source for Android's `BluetoothAdapter`. While it exposes state as one of `ON`, `OFF`, `TURNING_ON`, or `TURNING_OFF`, it has three extra states for internal use only: `BLE_ON`, `STATE_BLE_TURNING_ON`, and `BLE_TURNING_OFF`. When calling `BluetoothAdapter.getState`, these three internal states are treated as `OFF`. When you turn the Bluetooth setting off on an Android device (or at least, on _my_ Android device), it transitions to the `BLE_ON` state. 

If I had to guess, there is a difference here between Android's Airplane Mode and simply disabling Bluetooth, but I didn't go ahead and test that.
