### ISSUE TITLE
Writing is not permitted iOS

### ISSUE THREAD

**Issue by duanniston** [JuulLabs/kable#150]
Kotlin native, we trying to write characteristic, work in Android, but not work  in iOS,  observer characteristic in both  works perfectly  (WriteType.WithResponse)

**Comment by twyatt** [comment]
Thanks for reporting. Currently on vacation but I'll be back next week and try to find time to look into this.

**Comment by twyatt** [comment]
Can you provide logs using the `Data` log `level` (if you don't have sensitive data being transferred), or `Events` log `level` if you do?

See https://github.com/JuulLabs/kable#logging for details on setting up logging.
