### ISSUE TITLE
JS connection fails when characteristic has no descriptors

### ISSUE THREAD

**Issue by gregorbg** [JuulLabs/kable#179]
Kable version: `0.10.2`
Kotlin version: `1.5.31` (using `IR`)

Chrome version: `95.0.4638.54` (64 bit)

Upon trying to connect to my BLE device, I get the following error message:
```
SystemLogEngine.kt?d539:37 [Kable] z6FTIjgMta7LYVye0Uu2zQ== Unable to retrieve descriptor.
  service: 00001000-0000-1000-8000-00805f9b34fb
  characteristic: 00001001-0000-1000-8000-00805f9b34fb
DOMException: No Descriptors found in Characteristic.
```

By using a different, third-party BLE tool ("nRF Connect for Mobile" Android app) I have been able to establish that the characteristic mentioned in the error message indeed has no descriptors.
![kable_issue](https://user-images.githubusercontent.com/6136469/138272559-200a4e3f-c81f-402b-bf5b-758ec5b64682.png)

In terms of the source code, I have been able to figure out that...
1. Upon `connect`ing to a `Peripheral`, all Services are being queried and converted to `PlatformService`s: https://github.com/JuulLabs/kable/blob/0.10.2/core/src/jsMain/kotlin/Peripheral.kt#L178
2. For each individual Service, the Characteristics are in turn queried and converted to `PlatformCharacteristic`s: https://github.com/JuulLabs/kable/blob/0.10.2/core/src/jsMain/kotlin/PlatformService.kt#L24
3. Each individual Characteristic queries a list of descriptors: https://github.com/JuulLabs/kable/blob/0.10.2/core/src/jsMain/kotlin/PlatformCharacteristic.kt#L27
4. The Characteristic uses the external `getDescriptors` method in the Web Bluetooth API: https://github.com/JuulLabs/kable/blob/0.10.2/core/src/jsMain/kotlin/external/BluetoothRemoteGATTCharacteristic.kt#L19
5. That method seems to throw an error when there are no Descriptors (cf. the original error report "No Descriptors found in Characteristic", which triggers the catch handler in https://github.com/JuulLabs/kable/blob/0.10.2/core/src/jsMain/kotlin/PlatformCharacteristic.kt#L28

Please note that I am not knowledgeable enough in Bluetooth or BLE technology to understand what a Characteristic not having Descriptors even means, or whether it is allowed per the Bluetooth specifications. The device I am using is a Rubik's Cube that can track movements and rotations, cf. https://www.thecubicle.com/products/moyu-weilong-ai-3x3

Thank you for your awesome Kotlin library :smile:

**Comment by twyatt** [comment]
An update on this. I received the "MoYu WeiLong AI", but have not yet had time to revisit this issue. I'll try to find some time soon though.

**Comment by twyatt** [comment]
Tested the MoYu AI cube with the latest Kable ([0.35.0-rc](https://github.com/JuulLabs/kable/releases/tag/0.35.0-rc)) and it connected.

It does show the warning, as described in this issue:

```
[Kable/Connection] JTpZwOhvWUEltpUGE++lVA== Discovering services
SystemLogEngine.kt:27 [Kable/Connection] JTpZwOhvWUEltpUGE++lVA== Unable to retrieve descriptor.
  service: 00001000-0000-1000-8000-00805f9b34fb
  characteristic: 00001001-0000-1000-8000-00805f9b34fb
```

...but it does not result in a `DOMException: GATT operation failed for unknown reason.` failure.

Tried reading from `00001001-0000-1000-8000-00805f9b34fb` characteristic (as mentioned in https://github.com/JuulLabs/kable/issues/179#issue-1032416229) and it silently fails (as that characteristic is write-only).

Also tried observing `00001003-0000-1000-8000-00805f9b34fb` (as is listed in [BlueCubeModel.kt#L5](https://github.com/gregorbg/bluecube-kt/blob/9352703ce9aa39c918a01bb04da2ee985ab59088/library/src/commonMain/kotlin/net/gregorbg/cubing/hardware/bluetooth/BlueCubeModel.kt#L5) — linked project) and it subscribes to the characteristic but never gets any values:

```
[Kable] JTpZwOhvWUEltpUGE++lVA== Connecting
SystemLogEngine.kt:11 [Kable/Connection] JTpZwOhvWUEltpUGE++lVA== Discovering services
SystemLogEngine.kt:27 [Kable/Connection] JTpZwOhvWUEltpUGE++lVA== Unable to retrieve descriptor.
  service: 00001000-0000-1000-8000-00805f9b34fb
  characteristic: 00001001-0000-1000-8000-00805f9b34fb
SystemLogEngine.kt:11 [Kable] JTpZwOhvWUEltpUGE++lVA== Configuring characteristic observations
SystemLogEngine.kt:19 [Kable] JTpZwOhvWUEltpUGE++lVA== Connected
SystemLogEngine.kt:11 [Kable/Connection] JTpZwOhvWUEltpUGE++lVA== Starting observation
  service: 00001000-0000-1000-8000-00805f9b34fb
  characteristic: 00001003-0000-1000-8000-00805f9b34fb
SystemLogEngine.kt:11 [Kable/Connection] JTpZwOhvWUEltpUGE++lVA== addEventListener
  service: 00001000-0000-1000-8000-00805f9b34fb
  characteristic: 00001003-0000-1000-8000-00805f9b34fb
  event: characteristicvaluechanged
ConsoleLogger.kt:35 [SensorTag] Connected
```

Closing this issue, as everything seems to be working as expected in the [latest Kable version](https://github.com/JuulLabs/kable/releases/tag/0.35.0-rc).
