### ISSUE TITLE
Expose bond state as a flowable to be subscribed to

### ISSUE THREAD

**Issue by AyoTheDev** [JuulLabs/kable#192]
I think this would be a useful feature on an already amazing library, what do you think?

**Comment by twyatt** [comment]
Related to #111.

I haven't looked into it yet, but if only having bond state (without full bond support) is useful, then it might make sense to integrate this as a step towards full bonding support.

Thanks for the suggestion! I'll look into this when I pick up #111, which I _hope_ to get started on in the coming weeks.

**Comment by twyatt** [comment]
This will be covered by #111.
