### ISSUE TITLE
Drop JS `LEGACY` support

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/kable#243]

**Comment by burnhamd** [comment]
Curious what is driving the decision to drop javascript?

**Comment by twyatt** [comment]
Not dropping Javascript support, just dropping support for `LEGACY` compiler (and will only support [IR compiler](https://kotlinlang.org/docs/js-ir-compiler.html) moving forward).

**Comment by twyatt** [comment]
Going to postpone dropping `LEGACY` support, as IR compiler is still considered Beta. Assuming no major hurdles/headaches arise, I'd like to continue to support `LEGACY` until IR compiler is announced as stable.

**Comment by twyatt** [comment]
Watching https://youtrack.jetbrains.com/issue/KT-42289 for status updates on Kotlin/JS IR compiler becoming stable.

**Comment by twyatt** [comment]
Kotlin/JS IR backend is considered stable w/ 1.8.0, and legacy backend is now deprecated.
Support for legacy backend will be removed once Kable upgrades its Kotlin dependency to 1.8.0.
