### ISSUE TITLE
Request: Add bluetooth status for IOS CBCentralManager and Android BluetoothAdapter

### ISSUE THREAD

**Issue by burnhamd** [JuulLabs/kable#288]
Currently we are required to add code for checking the bluetooth status in the client application for seeing if bluetooth is enabled, turned on, and permissions are granted.  Would be nice to have a unified status flow which represented the state of the bluetooth on the system so that we can present errors and requests to the user in those cases.

Thinking there can be the following cases

- PoweredOn
-  Unauthorized (maybe with list of authorizations required?) This will be trickier for Android since there will also be location service involved.
-  Resetting
-  PoweredOff
-  Unknown
- Unsupported

**Comment by twyatt** [comment]
Related to #737, and sadly: we likely won't be supporting this in Kable, see #737 for the rationale.
