### ISSUE TITLE
iOS : Peer removed pairing information

### ISSUE THREAD

**Issue by francismariano** [JuulLabs/kable#334]
Hello everyone. It is mandatory to forget the peripheral in Bluetooth settings if the pairing keys was removed of the peripheral. Otherwise a fail to connect happens with code 14 and user info "Peer removed pairing information"

```
D/Kable: B99D740F-0DF8-E3D4-6F54-459FBAA4FB99 CentralManagerDelegate state change
  state: DidFailToConnect(identifier=B99D740F-0DF8-E3D4-6F54-459FBAA4FB99, error=Error Domain=CBErrorDomain Code=14 "Peer removed pairing information" UserInfo={NSLocalizedDescription=Peer removed pairing information})
```

The kable peripheral emits a new state  = Disconnected(status=Unknown(status=14)) but the connect function never is suspended with that fail. Maybe the connect function must fail with ConnectionRejectedException or whatever.

What do you think about that??

**Comment by twyatt** [comment]
>  It is mandatory to forget the peripheral in Bluetooth settings if the pairing keys was removed

Do you happen to have a code example of how that is done?

I'm not familiar with `centralManager:didFailToConnectPeripheral:error:` is supposed to work, so some example code for what is commonly done w/ that function would be helpful.

Also, what is the best way to test/reproduce this error?

**Comment by francismariano** [comment]
Hello folks.

Please see https://github.com/francismariano/kable/tree/issue-334
I put PeerRemovedPairingInformation as a new State and in connectAsync I called suspendUntilOrThrow to check if State.Connecting.Services is OK.

So, I can to do that:
```
try {
    peripheral.connect()
}  catch (e: ConnectionLostException) {
    val state = peripheral.state.first()
    if (state is State.Disconnected && state.status == State.Disconnected.Status.PeerRemovedPairingInformation) {
           Log.debug { "connect - PeerRemovedPairingInformation" }
    } else {
           Log.debug { "connect - ConnectionLostException" }
    }
 }
```

I think can have another better solution but that solves my problem for now.

**Comment by francismariano** [comment]
@twyatt Can I do a pull request replacing this line https://github.com/JuulLabs/kable/blob/3a043a0394b1d3c11ca23be8a342db1fe386ba98/core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt#L166 with `suspendUntilOrThrow<State.Connecting.Services>()`???

**Comment by twyatt** [comment]
@francismariano you're always welcome to create PRs — there is no harm to having dialog on a PR then ultimately closing it if we deem it unnecessary.
