### ISSUE TITLE
NoClassDefFoundError Failed resolution of: Lcom/juul/kable/ScannerKt

### ISSUE THREAD

**Issue by fedesenmartin** [JuulLabs/kable#349]
Hi 
Im working a multiplatform lib , and this was very helpful.
im deployed via local maven my multiplatform lib and imported in my android project.

The android app builds/install ok.But when i'm trying to do a scan 'ProxyManager().scan()' this is causing this crash.

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.juul.kable.ScannerKt" on path: DexPathList

Im using kotlin 1.5 version
multidex is enable in my android project
Any ideas?
Thanks!

**Comment by twyatt** [comment]
Sorry, I don't know what might be causing your issue.

Recent versions of Kable are compiled with Kotlin 1.7.0; I assume it'd be compatible (and unlikely to cause the issue you're seeing), but maybe try upgrading your Kotlin version (if possible)?
