### ISSUE TITLE
Too many receivers, total of 1000

### ISSUE THREAD

**Issue by nverinaud** [JuulLabs/kable#359]
In the context of my app I need to retrieve the peripheral in order to get the identifier.

The problem is that, on Android, it [registers a broadcast receiver](https://github.com/JuulLabs/kable/blob/main/core/src/androidMain/kotlin/Peripheral.kt#L137) every time and I quickly reach the limit of 1000 receivers which is prohibited by the OS.

I open this issue to discuss about ways to solve the problem in order to contribute by a pull request soon.

I suggest to share one broadcast receiver across all peripherals.

As a possible workaround, I will try to cancel the attached coroutine scope in order to [unregister the receiver](https://github.com/JuulLabs/kable/blob/main/core/src/androidMain/kotlin/Peripheral.kt#L146).

**Comment by twyatt** [comment]
Thanks for the report!

> I suggest to share one broadcast receiver across all peripherals.

I agree, this is likely the best approach.

> I open this issue to discuss about ways to solve the problem in order to contribute by a pull request soon.

My initial thought is that we'll want to have the single broadcast receiver you mentioned as an `internal object` and it will "broadcast" the BLE state to all peripherals by providing the state via a `MutableStateFlow`. Or, perhaps a `MutableSharedFlow` that only spins up the broadcast receiver when there is at least 1 subscriber.

**Comment by twyatt** [comment]
I haven't had a chance to test it yet, but the following `SNAPSHOT` build may fix this issue:

```kotlin
repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
    implementation("com.juul.kable:core:0.18.0-issue-359-1-SNAPSHOT")
}
```

**Comment by nverinaud** [comment]
Awesome ! I'm on vacation, I can check this starting august 22th. 😉

**Comment by twyatt** [comment]
Thanks so much for following up! I'll get it merged (and a new release out) soon; hopefully in the coming days.
