### ISSUE TITLE
[Suggestion] Add device name on Scanner Filters

### ISSUE THREAD

**Issue by PavlosTze** [JuulLabs/kable#377]
Right now, on the Filters we can only use `Services UUID` and `ManufacturerData`. I think it's important to be able to filter by device name (or at least a prefix of a device name). 

Is that feasible?

**Comment by twyatt** [comment]
> Is that feasible?

Yup.

Since Apple doesn't provide the functionality, it will only be available to Android and JS targets.

**Comment by PavlosTze** [comment]
That would be OK I think. Can we add both `name_prefix` and `name` options?
