### ISSUE TITLE
Support `autoConnect` on Android

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/kable#410]
As was mentioned in https://github.com/JuulLabs/kable/issues/365#issuecomment-1243022280, for some users having `autoConnect` hardcoded as `false` may cause connection troubles (specifically, GATT 133 errors).

Kable should provide an option to `connect` with `autoConnect` as `true`.

**Comment by JonatanPlesko** [comment]
Do you have any plans for this one?

I'm faced with a different situation where I want to keep a constant connection to a BLE device to observe and display its battery level. I would also like to avoid permanently blocking a thread with connection attempts (until a connection is established) and let the OS connect to the BLE device when available.

**Comment by twyatt** [comment]
It is planned, yes, but I'm super busy with work projects, so Kable rarely gets the as much love as I wish I could give it. 🙃 

I try to address Kable development in the following order:

1. features we need internally
2. community submitted PRs
3. issues marked as `bugs`
4. issues with the highest number of 👍 

There is talk of us potentially needing `autoConnect` internally, so this issue may get higher priority when/if that happens.
If you submit a PR I'll make time to help get that in.
Or, slap a 👍 on this issue. 😄

**Comment by twyatt** [comment]
Stackoverflow post with good info (for when I'm able to pick this up): https://stackoverflow.com/a/40187086
