### ISSUE TITLE
Improve testability/mockability via interfaces

### ISSUE THREAD

**Issue by charlee-dev** [JuulLabs/kable#474]
Hi. How do we test the kable? Mock Scanner and Advertisements?

**Comment by twyatt** [comment]
`Scanner` is an `interface`, so easily mockable; but `Advertisements` should be changed to an `interface`. 👍

**Comment by charlee-dev** [comment]
Yes, Scanner itself is not an issue, but Advertisements which is final... if you can abstract it with an interface, that would be great :) Thank you.

**Comment by twyatt** [comment]
Ya, I'll try to find some time soon to make `Advertisement` an `interface`. 👍

**Comment by charlee-dev** [comment]
From what I see, Android and iOS targets should be pretty straightforward. The Js one will need to change a little bit because of 
```kotlin
public open class AdvertisementImpl( // 1. Changed Advertisement to AdvertisementImpl
    private val advertisement: BluetoothAdvertisingEvent, // 3. 'public' function exposes its 'internal' parameter type BluetoothAdvertisingEvent
): Advertisement { ... } // 2. Extended interface Advertisement
```

**Comment by twyatt** [comment]
@charlee-dev does #479 fulfill the use-case you had?

_It will allow mocking of scanner and advertisements, but mocked advertisements won't be usable in `CoroutineScope.peripheral` builder functions._

**Comment by charlee-dev** [comment]
I have look. I only use it for scanning. I don't interact with any device.
