### ISSUE TITLE
NSInternalInconsistencyException on foreground scan on iOS

### ISSUE THREAD

**Issue by mtrewartha** [JuulLabs/kable#554]
After updating to v0.26.0, an `NSInternalInconsistencyException` seems to be thrown at `CentralManager.kt:43:36` with the following message:

>State restoration of CBCentralManager is only allowed for applications that have specified the \"bluetooth-central\" background mode"

We don't scan in the background, so we don't specify a background mode. I'm guessing this is related to #552? For now, we'll just hold off on the update as we don't need it.

**Comment by twyatt** [comment]
Thanks for reporting. It seems we need to make that functionality opt-in. 👍

**Comment by twyatt** [comment]
This will likely require some significant Kable API changes. I'm hopeful I'll be able to work on it soon and slate it for the next Kable release.

**Comment by mtrewartha** [comment]
Good to know and thanks for the quick response!

**Comment by twyatt** [comment]
> This will likely require some significant Kable API changes.

Ended up going with a solution (#561) that did not change the API significantly.
