### ISSUE TITLE
Help with iOS implementation

### ISSUE THREAD

**Issue by Codegn** [JuulLabs/kable#634]
Hello everyone,

First of all, thank you for the great work with Kable.

We have been successfully using Kable in an Android app, but we are at a bit of a loss trying to implement the same features in iOS. I was hoping that you could guide us through the steps that are necessary to use Kable with iOS since the examples provided are made for Android only.

Best regards!

**Comment by twyatt** [comment]
Unfortunately at this time I don't have the bandwidth to create an iOS example.

Perhaps you could try asking for pointers either in the [discussions](https://github.com/JuulLabs/kable/discussions) or on the `#juul-libraries` [kotlinlang](https://kotlinlang.org/community/) Slack?

**Comment by twyatt** [comment]
Closing as duplicate of https://github.com/JuulLabs/sensortag/issues/11.
