### ISSUE TITLE
To expose device's bond state 

### ISSUE THREAD

**Issue by francismariano** [JuulLabs/kable#65]
Hello guys,

Is it possible to expose the device's bond state on Advertisement class? For example:

```
public actual class Advertisement(
    private val scanResult: ScanResult,
) {

    internal val bluetoothDevice: BluetoothDevice
        get() = scanResult.device

    public actual val name: String?
        get() = bluetoothDevice.name
        
    public actual val bondState: String?
        get() = bluetoothDevice.bondState
        
    .......
}
```

**Comment by twyatt** [comment]
Seems reasonable. From a quick search, it appears this status is [unavailable for Apple](https://punchthrough.com/core-bluetooth-basics/#Pairing-and-bonding) and JavaScript, so this can be an Android specific property.

**Comment by twyatt** [comment]
Until [0.4.0](https://github.com/JuulLabs/kable/milestone/4) is released, this can be tested via:

```kotlin
import java.net.URI

repositories {
    maven { url = URI("https://oss.sonatype.org/content/repositories/snapshots") }
}

dependencies {
    implementation("com.juul.kable:core:0.3.0-issue-65-SNAPSHOT")
}
```
