### ISSUE TITLE
iOS Advertisement isConnectable always null

### ISSUE THREAD

**Issue by R4leven** [JuulLabs/kable#697]
Hi,

We want to filter out non-connectable BLE devices based on some conditions and are using the isConnectable flag on the Advertisement.

The flag works on Android, but on iOS it is always null, even for connectable devices.

Maybe the cast of the CBAdvertisementDataIsConnectable value to Boolean is not working correctly.

https://github.com/JuulLabs/kable/blob/aee205e9127853752c06e5d62a87590cbbf3aabf/core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt#L43

I tested it without KMP and a CBCentralManager on iOS and the value was set to 1.
Perhaps the value needs to be cast to NSNumber (which is stated here: https://developer.apple.com/documentation/corebluetooth/cbadvertisementdataisconnectable) and then the boolValue needs to be used.

![image](https://github.com/JuulLabs/kable/assets/9137372/9b88c995-7bdf-4fbf-b0f8-d435defd5e65)

using com.juul.kable:core:0.31.1 and iOS 17.5.1

**Comment by twyatt** [comment]
Aw yes, that looks like a bug. Thanks for the thorough analysis of the issue! I'll get a fix up soon.

**Comment by twyatt** [comment]
@R4leven let me know if you need me to back port the fix to Kable 0.32.x (i.e. if you're not ready for Kable 0.33.x w/ K2 upgrade yet).

**Comment by R4leven** [comment]
Thank you for the quick reply and fix. We are planning on upgrading to 0.33.x soon, so no back port is needed.
