### ISSUE TITLE
How to forcefully stop an ongoing scan 

### ISSUE THREAD

**Issue by surame8288** [JuulLabs/kable#718]
Could you kindly explain how to forcefully stop  an ongoing scan? I want to time out an active scan if no advertisements are located in the area.

**Comment by twyatt** [comment]
Have you tried using the [`timeout`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/timeout.html) operator on the `advertisements` flow?
