### ISSUE TITLE
On the iOS platform, no request for changing the MTU size is provided.

### ISSUE THREAD

**Issue by surame8288** [JuulLabs/kable#719]
Hello, everyone. I'm working on a Comose multiplatform project. Can somebody in this group tell me how to request a change in the MTU size on the iOS platform? I notice we have an option for doing it on Android, but not iOS.

**Comment by twyatt** [comment]
iOS (Core Bluetooth) does not allow setting the MTU size (from the central). Your peripheral can set the MTU (within limits) and Core Bluetooth should honor it.

https://stackoverflow.com/a/68389331
