### ISSUE TITLE
Feature request: Add maximumWriteValueLengthForType to iOS Peripheral

### ISSUE THREAD

**Issue by NaiRo94s** [JuulLabs/kable#729]
Hi, 
it would be great if you could add [maximumWriteValueLengthForType](https://developer.apple.com/documentation/corebluetooth/cbperipheral/maximumwritevaluelength(for:)) to the CoreBluetoothPeripheral interface.

Sample: 

```
    override fun maximumWriteValueLengthForType(writeType: WriteType): Int {
        val type = when (writeType) {
            WithResponse -> CBCharacteristicWriteWithResponse
            WithoutResponse -> CBCharacteristicWriteWithoutResponse
        }
        return cbPeripheral.maximumWriteValueLengthForType(type).toInt()
    }
```

**Comment by twyatt** [comment]
Thanks for the code snippet. This would be a good addition. I'll try to add it soon.

**Comment by matttbates** [comment]
Hey Travis, I have a use-case that requires this functionality. Are there any plans to add this in the near future? Thank you for your support and for a solid KMP library.

**Comment by twyatt** [comment]
I would like to get to this sooner rather than later, but not sure I'll have much bandwidth in the near term.
I may be able to find some time after getting a final `0.35.0` release out.

**Comment by twyatt** [comment]
PRs are also welcome, and I try to prioritize them above most other work I have on my plate. 😉

**Comment by ErikHellman** [comment]
I made a PR implementing this. I haven't been able to test this properly, but as I'm only reading data I believe this should be fairly safe in any case.
