### ISSUE TITLE
[Feedback `0.35.0-RC`]: Peripheral Constructor should allow address

### ISSUE THREAD

**Issue by PavlosTze** [JuulLabs/kable#790]
With `0.34.0` it was possible to create a `Peripheral` based on the MAC Address of the advertisement. If there is no specific reason of removing this functionality in `0.35.0`, I suggest to include it as well as it's easier to not having to carry an `Advertisement` object but carry just a `String` throughout our app.

**Comment by twyatt** [comment]
It was an oversight that it was removed. Thanks for catching that. It will be back in `0.35.0-rc1`.
