### ISSUE TITLE
iOS API misuse warning

### ISSUE THREAD

**Issue by ln-12** [JuulLabs/kable#81]
I think that I came across a small flaw in the `Advertisement` cleanup [here](https://github.com/JuulLabs/kable/blob/c469772eb0660c96e2722e7c952b3f7ac8bbf331/core/src/appleMain/kotlin/Scanner.kt#L31). When bluetooth is turned on, everything works fine. But in the case that I open the screen, turn off bluetooth and leave it, I get the following warning:
```
[CoreBluetooth] API MISUSE: <CBCentralManager: 0x2831be780> can only accept this command while in the powered on state
```
I know that this case is not very likely to happen, but for the sake of correctness, `central.stopScan()` should only be called if the state is `.poweredOn `.

**Comment by twyatt** [comment]
Thanks for reporting, and the insight on how to fix. I'll create a fix when I have a chance.
